# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-13 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('data_lancamento', models.DateField()),
                ('avaliacao', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('data', models.DateField()),
                ('genero', models.TextField()),
                ('avaliacao', models.FloatField()),
                ('id_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Album')),
            ],
        ),
        migrations.CreateModel(
            name='Musico',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('origem', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='id_musico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Musico'),
        ),
    ]
